### ISSUE TITLE
Ip2location.new.open('IP2LOCATION-LITE-DB1.BIN') expand_path weirdness

### ISSUE THREAD

**Issue by blackjackshellac** [ip2location/ip2location-ruby#1]
On line 14 of lib/ip2location_ruby.rb 'rb' is inserted into the path of the given "url".

```
 def open(url)
    self.file = File.open(File.expand_path url, 'rb')
    i2l = Ip2locationConfig.read(file)
```
This forces the database to be in the rb subdirectory of the directory in which the database file exists if I use a relative pathname,

```
File.expand_path('IP2LOCATION-LITE-DB1.BIN', 'rb')
=> "/home/tmp/foo/ip2location/rb/IP2LOCATION-LITE-DB1.BIN"

```
Is there some reason this is being done? Because it means I have to store the database file in a subdirectory called 'rb' even if I attempt to open "./IP2LOCATION-LITE-DB1.BIN"

```
irb(main):028:0> Dir.chdir("/home/tmp/foo/ip2location") {
irb(main):029:1* File.expand_path './IP2LOCATION-LITE-DB1.BIN', 'rb'
irb(main):030:1> }
=> "/home/tmp/foo/ip2location/rb/IP2LOCATION-LITE-DB1.BIN"

```

The dir_string 'rb' is only inserted into the path for certain relative file paths, if I use a full filespec to point to the file expand_path does not insert the 'rb' directory into the output,

```
irb(main):013:0> File.expand_path('/home/tmp/foo/ip2location/IP2LOCATION-LITE-DB1.BIN', 'rb')
=> "/home/tmp/foo/ip2location/IP2LOCATION-LITE-DB1.BIN"

```
This is on,

```
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

```

**Comment by blackjackshellac** [comment]
BTW, I can avoid this issue with a work around like,

`ip2=Ip2location.new.open(File.expand_path('./IP2LOCATION-LITE-DB1.BIN'))
`

I just find it kind of unexpected, if not unintended.

**Comment by ip2location-com** [comment]
The purpose of the "rb" sub-directory is to ease maintenance of database, because we have many type of database.

As you have found the work around, you may go with it.
