### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by InvaQ** [ip2location/ip2location-ruby#3]
It's not obvious that the data should be placed in the `rb` folder, please mention this in the `README`.
without knowing it, you also run into an incomprehensible error

`i2l = Ip2location.new.open("IP-COUNTRY-SAMPLE.BIN")`
`=>
Ip2location.new.open() error in opening IP-COUNTRY-SAMPLE.BIN.`

the full path should be displayed for clarity of the error 
`Errno::ENOENT: No such file or directory @ rb_sysopen - /your/path/rb/IP-COUNTRY-SAMPLE.BIN`

or just leave clean input path

`self.file = File.open(File.expand_path url)`

https://github.com/ip2location/ip2location-ruby/blob/e6dfdb9d02fb61b0c80a937d3f8ee23e74b52c99/lib/ip2location_ruby.rb#L29

**Comment by ip2location-com** [comment]
Thank you for the input. We have updated it.
